### ISSUE TITLE
German Support

### ISSUE THREAD

**Issue by jhoelzl** [DanielJDufour/language-detector#1]
Hi,

it would be nice if you could add german as detection language. Thanks!

**Comment by DanielJDufour** [comment]
Just did!  Let me know how it goes!  Danke :)

**Comment by jhoelzl** [comment]
Works! (limited, but works :) )

**Comment by DanielJDufour** [comment]
@jhoelzl , I wanted to let you know I just added some code that greatly improves the accuracy by about 30% up to 93.55%.  I also pushed language-detector to pypi, so you should be able to just update through pip as your normally would.

**Comment by jhoelzl** [comment]
@DanielJDufour thanks, i will try!
